import models
from database import SessionLocal
import random
import bcrypt

# Définition de plusieurs corps de métiers et types de prestations
corps_metiers = [
    {
        "nom": "Informatique",
        "prestations": [
            ("Développement site web vitrine", "Création d'un site web vitrine pour présenter une entreprise."),
            ("Développement site e-commerce", "Mise en place d'une boutique en ligne avec paiement sécurisé."),
            ("Développement application mobile iOS", "Conception d'une app native pour iPhone/iPad."),
            ("Développement application mobile Android", "Conception d'une app native pour Android."),
            ("Refonte graphique d'un site web", "Modernisation du design et de l'ergonomie d'un site existant."),
            ("Intégration API de paiement", "Ajout d'un module de paiement Stripe/Paypal sur un site."),
            ("Déploiement infrastructure cloud AWS", "Mise en place d'une architecture scalable sur AWS."),
            ("Déploiement infrastructure cloud Azure", "Mise en place d'une architecture scalable sur Azure."),
            ("Déploiement infrastructure cloud GCP", "Mise en place d'une architecture scalable sur Google Cloud."),
            ("Audit de sécurité informatique", "Analyse des vulnérabilités et recommandations de sécurité."),
            ("Optimisation SEO avancée", "Amélioration du référencement naturel sur Google."),
            ("Maintenance applicative annuelle", "Support, mises à jour et corrections de bugs sur 1 an."),
            ("Formation utilisateurs back-office", "Formation à l'utilisation d'un CMS ou d'un ERP."),
            ("Développement API REST", "Conception et documentation d'API RESTful."),
            ("Développement API GraphQL", "Conception et documentation d'API GraphQL."),
            ("Développement logiciel embarqué", "Programmation de systèmes embarqués (IoT, domotique, etc.)."),
            ("Développement chatbot IA", "Création de chatbot pour site web ou messagerie."),
            ("Développement script d'automatisation", "Automatisation de tâches répétitives (Python, Bash, etc.)."),
            ("Déploiement CI/CD", "Mise en place de pipelines d'intégration et déploiement continu."),
            ("Tests automatisés", "Écriture et exécution de tests unitaires et fonctionnels."),
            ("Migration de base de données", "Transfert de données et migration de schéma."),
            ("Développement plugin WordPress", "Création de plugins personnalisés pour WordPress."),
            ("Développement module Prestashop", "Création de modules personnalisés pour Prestashop."),
            ("Développement extension navigateur", "Création d'extensions Chrome/Firefox."),
            ("Développement application desktop", "Applications Windows/Mac/Linux sur mesure."),
            ("Développement microservices", "Architecture et développement de microservices."),
            ("Développement site multilingue", "Sites web avec gestion avancée des langues."),
            ("Développement site accessible", "Sites web respectant les normes d'accessibilité."),
            ("Développement site mobile first", "Sites web optimisés pour mobile."),
            ("Développement PWA", "Progressive Web Apps pour expérience mobile avancée."),
            ("Développement SaaS", "Applications web en mode Software as a Service."),
            ("Développement CRM sur mesure", "Outil de gestion de la relation client personnalisé."),
            ("Développement ERP sur mesure", "Outil de gestion d'entreprise personnalisé."),
            ("Développement e-learning", "Plateforme de formation en ligne sur mesure."),
            ("Développement marketplace", "Plateforme de mise en relation acheteurs/vendeurs."),
            ("Développement site événementiel", "Sites web pour événements, conférences, salons."),
            ("Développement site portfolio", "Sites web pour présenter un portfolio professionnel."),
            ("Développement site associatif", "Sites web pour associations et ONG."),
            ("Développement d'application blockchain", "Création de smart contracts et d'applications décentralisées (dApp)."),
            ("Développement de jeux vidéo 2D", "Conception et développement de jeux vidéo en 2D pour PC et mobile."),
            ("Développement de jeux vidéo 3D", "Conception et développement de jeux vidéo en 3D pour PC et consoles."),
            ("Développement de simulateur VR", "Création d'applications de réalité virtuelle pour formation ou divertissement."),
            ("Développement d'API d'intelligence artificielle", "Mise à disposition d'API pour la reconnaissance d'image, de texte, etc."),
            ("Développement d'outils de data visualisation", "Création de dashboards interactifs pour l'analyse de données."),
            ("Développement d'algorithmes de machine learning", "Conception et entraînement de modèles prédictifs sur mesure."),
            ("Développement d'applications IoT", "Applications connectées pour objets intelligents (domotique, capteurs, etc.)."),
            ("Développement d'outils de scraping web", "Extraction automatisée de données sur des sites web publics."),
            ("Développement d'outils de cybersécurité", "Création de solutions de détection d'intrusion et de protection réseau."),
            ("Développement d'outils de gestion documentaire", "Systèmes de GED pour entreprises et collectivités."),
            ("Développement d'outils de signature électronique", "Solutions de signature légale de documents en ligne."),
            ("Développement d'outils de visioconférence", "Création de plateformes de réunion vidéo sécurisées."),
            ("Développement d'outils de gestion RH", "Applications pour la gestion des congés, paie, recrutement, etc."),
            ("Développement d'outils de gestion de projet agile", "Solutions pour le suivi de projets Scrum/Kanban."),
            ("Développement d'outils de gestion de flotte", "Applications pour le suivi et la maintenance de véhicules d'entreprise."),
            ("Développement d'outils de gestion de stock", "Solutions pour l'inventaire et la logistique."),
            ("Développement d'outils de gestion de planning", "Applications pour la planification de ressources et d'équipes."),
            ("Développement d'outils de gestion de tickets", "Systèmes de support client et helpdesk."),
            ("Développement d'outils de gestion de facturation", "Automatisation de la création et l'envoi de factures."),
            ("Développement d'outils de gestion de newsletters", "Solutions pour l'envoi massif d'e-mails marketing."),
            ("Développement d'outils de gestion de campagnes SMS", "Plateformes pour l'envoi de SMS en masse."),
            ("Développement d'outils de gestion de rendez-vous", "Applications pour la prise de rendez-vous en ligne."),
            ("Développement d'outils de gestion de réservations", "Systèmes de réservation pour hôtels, restaurants, etc."),
            ("Développement d'outils de gestion de notes de frais", "Applications pour la gestion et le remboursement des frais professionnels."),
            ("Développement d'outils de gestion de formations", "Plateformes pour la gestion des sessions de formation et des apprenants."),
            ("Développement d'outils de gestion de maintenance", "Applications pour le suivi des interventions techniques."),
            ("Développement d'outils de gestion de conformité RGPD", "Solutions pour la gestion des consentements et des données personnelles."),
            ("Développement d'outils de gestion de contrats", "Applications pour la rédaction, le suivi et l'archivage des contrats."),
            ("Développement d'outils de gestion de flotte mobile", "Suivi et gestion des appareils mobiles d'entreprise."),
            ("Développement d'outils de gestion de parc informatique", "Inventaire et gestion des équipements informatiques."),
            ("Développement d'outils de gestion de sécurité réseau", "Surveillance et protection des réseaux d'entreprise."),
            ("Développement d'outils de gestion de sauvegarde", "Solutions de backup et restauration de données."),
            ("Développement d'outils de gestion de licences logicielles", "Suivi et gestion des licences pour les logiciels d'entreprise."),
            ("Développement d'outils de gestion de conformité logicielle", "Vérification et audit des usages logiciels."),
            ("Développement d'outils de gestion de parc automobile", "Gestion des véhicules, entretiens, et sinistres."),
            ("Développement d'outils de gestion de flotte de drones", "Suivi et gestion des drones professionnels."),
            ("Développement d'outils de gestion de bornes de recharge", "Gestion des bornes pour véhicules électriques."),
            ("Développement d'outils de gestion de capteurs industriels", "Suivi et analyse des données de capteurs en usine."),
            ("Développement d'outils de gestion de production industrielle", "Suivi des chaînes de production et des stocks."),
            ("Développement d'outils de gestion de maintenance prédictive", "Anticipation des pannes grâce à l'IA."),
            ("Développement d'outils de gestion de la relation client omnicanale", "Centralisation des interactions clients sur tous les canaux."),
            ("Développement d'outils de gestion de la satisfaction client", "Enquêtes et analyses de feedback clients."),
            ("Développement d'outils de gestion de la fidélisation client", "Programmes de fidélité et récompenses."),
            ("Développement d'outils de gestion de la réputation en ligne", "Surveillance et gestion des avis et notations."),
            ("Développement d'outils de gestion de la conformité PCI DSS", "Sécurisation des paiements et conformité bancaire."),
            ("Développement d'outils de gestion de la conformité HDS", "Gestion des données de santé hébergées."),
            ("Développement d'outils de gestion de la conformité ISO 27001", "Mise en conformité sécurité de l'information."),
            ("Développement d'outils de gestion de la conformité SOX", "Contrôle interne et conformité financière."),
            ("Développement d'outils de gestion de la conformité GDPR", "Gestion des droits et obligations RGPD."),
            ("Développement d'outils de gestion de la conformité HIPAA", "Protection des données de santé aux USA."),
            ("Développement d'outils de gestion de la conformité CCPA", "Protection des données personnelles en Californie."),
            ("Développement d'outils de gestion de la conformité eIDAS", "Signature électronique et identité numérique européenne."),
            ("Développement d'outils de gestion de la conformité LPM", "Sécurité des OIV (opérateurs d'importance vitale)."),
            ("Développement d'outils de gestion de la conformité RGAA", "Accessibilité numérique pour les services publics."),
            ("Développement d'outils de gestion de la conformité SAPIN 2", "Lutte contre la corruption et conformité française."),
            ("Développement d'outils de gestion de la conformité DORA", "Résilience opérationnelle numérique dans la finance."),
            ("Développement d'outils de gestion de la conformité NIS 2", "Sécurité des réseaux et systèmes d'information européens."),
        ]
    },
    {
        "nom": "Bâtiment",
        "prestations": [
            ("Construction de maison individuelle", "Réalisation complète d'une maison clé en main."),
            ("Rénovation d'appartement", "Travaux de rénovation tous corps d'état."),
            ("Pose de carrelage", "Fourniture et pose de carrelage intérieur/extérieur."),
            ("Installation de plomberie salle de bain", "Création ou rénovation complète d'une salle de bain."),
            ("Mise aux normes électriques", "Remise à neuf de l'installation électrique selon la norme NF C 15-100."),
            ("Isolation thermique des combles", "Pose d'isolant pour améliorer la performance énergétique."),
            ("Peinture intérieure murs et plafonds", "Préparation et application de peinture professionnelle."),
            ("Ravalement de façade", "Nettoyage, réparation et peinture de façade extérieure."),
            ("Création de terrasse bois", "Conception et pose d'une terrasse en bois sur mesure."),
            ("Menuiserie sur mesure", "Fabrication et pose de meubles ou rangements personnalisés."),
            ("Réfection toiture tuiles", "Remplacement ou réparation de tuiles et étanchéité."),
            ("Installation de fenêtres PVC", "Pose de fenêtres double vitrage en PVC."),
            ("Aménagement de combles", "Transformation de combles en espace habitable."),
            ("Création d'escalier sur mesure", "Conception et installation d'escaliers personnalisés."),
            ("Installation de portail motorisé", "Pose et motorisation de portails extérieurs."),
            ("Installation de climatisation", "Mise en place de systèmes de climatisation réversible."),
            ("Installation de pompe à chaleur", "Pose de PAC air/eau ou air/air."),
            ("Création de véranda", "Construction de vérandas sur mesure."),
            ("Installation de panneaux solaires", "Pose de panneaux photovoltaïques pour autoconsommation."),
            ("Rénovation énergétique globale", "Travaux d'isolation, chauffage, menuiseries pour économies d'énergie."),
            ("Installation de cuisine équipée", "Conception et pose de cuisines sur mesure."),
            ("Création de salle de sport à domicile", "Aménagement d'une pièce dédiée au sport."),
            ("Installation d'alarme maison", "Pose de systèmes d'alarme et vidéosurveillance."),
            ("Création de piscine enterrée", "Construction de piscines sur mesure."),
            ("Installation de spa/jacuzzi", "Pose de spas et jacuzzis d'intérieur ou extérieur."),
            ("Création de mur végétal intérieur", "Installation de murs végétalisés pour décoration."),
            ("Installation de parquet massif", "Pose de parquet bois massif ou contrecollé."),
            ("Création de dressing sur mesure", "Conception et installation de dressings personnalisés."),
            ("Installation de volets roulants", "Pose de volets électriques ou manuels."),
            ("Création de garage attenant", "Construction de garages accolés à la maison."),
            ("Création d'abri de jardin", "Construction d'abris de jardin en bois ou métal."),
            ("Installation de gouttières alu", "Pose de gouttières en aluminium sur mesure."),
            ("Création de clôture extérieure", "Installation de clôtures pour sécuriser le terrain."),
            ("Création de pergola bioclimatique", "Installation de pergolas à lames orientables."),
            ("Création de cave à vin", "Aménagement de caves à vin enterrées ou en intérieur."),
            ("Création de local technique piscine", "Construction de locaux techniques pour piscines."),
            ("Démolition de bâtiment", "Démolition contrôlée de structures existantes."),
            ("Construction de murs de soutènement", "Édification de murs pour retenir la terre ou l'eau."),
            ("Installation de plancher chauffant", "Pose de systèmes de chauffage au sol hydrauliques ou électriques."),
            ("Création de mezzanine", "Ajout d'un espace surélevé pour optimiser la surface habitable."),
            ("Installation d'ascenseur privatif", "Mise en place d'ascenseurs pour maisons individuelles."),
            ("Création de toiture végétalisée", "Installation de toits recouverts de végétation pour isolation et écologie."),
            ("Installation de bornes de recharge électrique", "Pose de bornes pour véhicules électriques."),
            ("Création de murs antibruit", "Construction de murs pour réduire les nuisances sonores."),
            ("Installation de domotique maison", "Automatisation de l'éclairage, chauffage, sécurité, etc."),
            ("Création de salle home cinéma", "Aménagement d'une pièce dédiée au cinéma à domicile."),
            ("Installation de panneaux solaires thermiques", "Production d'eau chaude sanitaire par énergie solaire."),
            ("Création de toiture terrasse", "Transformation de toits plats en terrasses accessibles."),
            ("Installation de stores bannes", "Pose de stores extérieurs motorisés ou manuels."),
            ("Création de fontaine de jardin", "Installation de fontaines décoratives ou fonctionnelles."),
            ("Installation de système de récupération d'eau de pluie", "Mise en place de cuves et réseaux pour arrosage ou sanitaires."),
            ("Création de cave enterrée", "Construction de caves pour stockage ou vinification."),
            ("Installation de sauna", "Pose de saunas traditionnels ou infrarouges."),
            ("Création de mur en pierre sèche", "Montage de murs sans liant pour esthétique et drainage."),
            ("Installation de garde-corps inox", "Pose de protections pour escaliers, balcons, terrasses."),
            ("Création de passerelle extérieure", "Construction de passerelles piétonnes ou techniques."),
            ("Installation de puits de lumière", "Ajout de fenêtres de toit pour éclairage naturel."),
            ("Création de caveau funéraire", "Construction de caveaux dans les cimetières."),
            ("Installation de système d'arrosage automatique", "Pose de réseaux d'arrosage programmables."),
            ("Création de mur rideau vitré", "Façades vitrées pour bâtiments modernes."),
            ("Installation de plancher technique surélevé", "Pose de planchers pour passage de câbles et réseaux."),
            ("Création de salle blanche", "Aménagement d'espaces à atmosphère contrôlée pour industrie ou santé."),
            ("Installation de système anti-inondation", "Pose de barrières et pompes pour protéger les bâtiments."),
            ("Création de terrasse sur pilotis", "Construction de terrasses surélevées pour terrains en pente."),
            ("Installation de système de ventilation double flux", "Pose de VMC pour renouvellement d'air et économies d'énergie."),
            ("Création de mur végétalisé extérieur", "Installation de murs verts pour façade ou clôture."),
            ("Installation de système de chauffage bois", "Pose de poêles, chaudières ou inserts à bois."),
            ("Création de salle de bain PMR", "Aménagement de salles de bain accessibles aux personnes à mobilité réduite."),
            ("Installation de système de vidéosurveillance", "Pose de caméras et enregistreurs pour sécurité."),
            ("Création de local vélo sécurisé", "Aménagement d'espaces de stationnement pour vélos."),
            ("Installation de système de filtration piscine", "Pose de filtres et pompes pour piscines privées."),
            ("Création de terrasse en pierre naturelle", "Pose de dalles ou pavés en pierre pour terrasses."),
            ("Installation de système d'alarme incendie", "Pose de détecteurs et alarmes pour la sécurité incendie."),
            ("Création de salle de jeux enfants", "Aménagement d'espaces ludiques et sécurisés."),
            ("Installation de système de chauffage solaire", "Pose de capteurs solaires pour chauffage central."),
            ("Création de serre de jardin", "Construction de serres pour culture potagère ou ornementale."),
            ("Installation de système d'éclairage LED extérieur", "Pose de luminaires basse consommation pour jardins et allées."),
            ("Création de terrasse couverte", "Construction de toitures pour terrasses existantes."),
        ]
    },
    {
        "nom": "Santé",
        "prestations": [
            ("Consultation médecine générale", "Bilan de santé, diagnostic et prescription médicale."),
            ("Consultation pédiatrique", "Suivi médical des enfants et vaccinations."),
            ("Soins infirmiers à domicile", "Injections, pansements, suivi post-opératoire."),
            ("Séance de kinésithérapie", "Rééducation après blessure ou chirurgie."),
            ("Consultation diététique", "Élaboration de plans alimentaires personnalisés."),
            ("Séance de psychologie individuelle", "Accompagnement psychologique et thérapie."),
            ("Atelier gestion du stress", "Techniques de relaxation et gestion émotionnelle."),
            ("Prise de sang à domicile", "Réalisation de prélèvements sanguins à domicile."),
            ("Vaccination grippe/covid", "Administration de vaccins saisonniers."),
            ("Suivi grossesse sage-femme", "Consultations prénatales et préparation à l'accouchement."),
            ("Consultation addictologie", "Accompagnement au sevrage tabac, alcool, etc."),
            ("Consultation cardiologie", "Bilan cardiaque et suivi des pathologies."),
            ("Consultation dermatologie", "Diagnostic et traitement des maladies de la peau."),
            ("Consultation ophtalmologie", "Bilan visuel et prescription de lunettes."),
            ("Consultation ORL", "Diagnostic et traitement des troubles ORL."),
            ("Consultation gynécologie", "Suivi gynécologique et dépistage."),
            ("Consultation orthopédie", "Diagnostic et traitement des pathologies de l'appareil locomoteur."),
            ("Consultation endocrinologie", "Suivi des troubles hormonaux et métaboliques."),
            ("Consultation neurologie", "Diagnostic et suivi des maladies du système nerveux."),
            ("Consultation psychiatrie", "Prise en charge des troubles psychiatriques."),
            ("Consultation pneumologie", "Diagnostic et traitement des maladies respiratoires."),
            ("Consultation rhumatologie", "Suivi des maladies articulaires et osseuses."),
            ("Consultation gastro-entérologie", "Diagnostic et traitement des maladies digestives."),
            ("Consultation urologie", "Suivi des pathologies urinaires et génitales."),
            ("Consultation allergologie", "Dépistage et traitement des allergies."),
            ("Consultation nutrition sportive", "Conseils diététiques pour sportifs."),
            ("Consultation tabacologie", "Aide au sevrage tabagique."),
            ("Consultation sexologie", "Conseil et accompagnement en santé sexuelle."),
            ("Consultation gériatrie", "Suivi médical des personnes âgées."),
            ("Consultation pédo-psychiatrie", "Prise en charge des troubles psychiques de l'enfant."),
            ("Consultation podologie", "Soins des pieds et conseils orthopédiques."),
            ("Consultation ostéopathie", "Manipulations pour soulager douleurs et troubles fonctionnels."),
            ("Consultation sophrologie", "Techniques de relaxation et gestion du stress."),
            ("Consultation hypnose", "Accompagnement par l'hypnose thérapeutique."),
            ("Consultation télé-médecine", "Consultation médicale à distance par visioconférence."),
            ("Bilan de santé complet", "Examen médical approfondi avec analyses biologiques."),
            ("Dépistage cancer colorectal", "Test de dépistage et suivi médical."),
            ("Dépistage cancer du sein", "Mammographie et suivi spécialisé."),
            ("Dépistage diabète", "Analyse de la glycémie et conseils de prévention."),
            ("Dépistage MST/IST", "Tests et accompagnement pour infections sexuellement transmissibles."),
            ("Vaccination voyage", "Vaccins obligatoires et conseils santé pour voyageurs."),
            ("Consultation addictologie numérique", "Accompagnement des addictions aux écrans et jeux vidéo."),
            ("Consultation troubles du sommeil", "Diagnostic et traitement des insomnies et apnées."),
            ("Consultation troubles alimentaires", "Prise en charge de l'anorexie, boulimie, etc."),
            ("Consultation troubles bipolaires", "Suivi psychiatrique spécialisé."),
            ("Consultation troubles autistiques", "Diagnostic et accompagnement des TSA."),
            ("Consultation troubles de l'attention", "Diagnostic et suivi TDAH."),
            ("Consultation mémoire", "Bilan neuropsychologique pour troubles de la mémoire."),
            ("Consultation post-AVC", "Rééducation et suivi après accident vasculaire cérébral."),
            ("Consultation post-chirurgie", "Suivi médical après intervention chirurgicale."),
            ("Consultation post-cancer", "Accompagnement et suivi après traitement oncologique."),
            ("Consultation douleur chronique", "Prise en charge pluridisciplinaire de la douleur."),
            ("Consultation infertilité", "Diagnostic et accompagnement des troubles de la fertilité."),
            ("Consultation procréation médicalement assistée", "Suivi PMA et FIV."),
            ("Consultation gériatrique à domicile", "Visite médicale pour personnes âgées dépendantes."),
            ("Consultation soins palliatifs", "Accompagnement en fin de vie."),
            ("Consultation nutritionniste sportif", "Suivi diététique pour sportifs de haut niveau."),
            ("Consultation tabacologue en entreprise", "Prévention et accompagnement au sevrage tabagique en milieu professionnel."),
            ("Consultation sexologue en ligne", "Accompagnement à distance en santé sexuelle."),
            ("Consultation psychologue scolaire", "Accompagnement des enfants en milieu scolaire."),
            ("Consultation ergothérapeute", "Rééducation de l'autonomie et de la motricité."),
            ("Consultation orthophoniste", "Prise en charge des troubles du langage et de la communication."),
            ("Consultation diététicien en ligne", "Conseils nutritionnels à distance."),
            ("Consultation podologue du sport", "Soins des pieds pour sportifs."),
            ("Consultation ostéopathe à domicile", "Manipulations et soins à domicile."),
            ("Consultation sophrologue en entreprise", "Gestion du stress et bien-être au travail."),
            ("Consultation hypnothérapeute en ligne", "Séances d'hypnose à distance."),
            ("Consultation psychomotricien", "Rééducation des troubles psychomoteurs."),
            ("Consultation orthoptiste", "Rééducation des troubles de la vision."),
            ("Consultation audioprothésiste", "Bilan auditif et adaptation d'appareils."),
            ("Consultation diététicien hospitalier", "Suivi nutritionnel en milieu hospitalier."),
            ("Consultation psychologue du travail", "Accompagnement des salariés en entreprise."),
            ("Consultation sexologue pour couples", "Thérapie de couple et sexualité."),
            ("Consultation addictologue adolescent", "Prise en charge des addictions chez les jeunes."),
            ("Consultation psychologue clinicien", "Accompagnement psychologique spécialisé."),
            ("Consultation psychiatre expert judiciaire", "Expertise psychiatrique pour la justice."),
            ("Consultation médecin du sport", "Suivi médical des sportifs amateurs et professionnels."),
            ("Consultation médecin du travail", "Suivi de la santé des salariés."),
            ("Consultation médecin légiste", "Expertise médicale en cas de litige ou décès."),
        ]
    },
    {
        "nom": "Éducation",
        "prestations": [
            ("Cours particuliers mathématiques", "Soutien scolaire en maths collège/lycée."),
            ("Cours particuliers anglais", "Remise à niveau et préparation examens d'anglais."),
            ("Préparation au bac français", "Coaching et méthodologie pour réussir l'épreuve écrite et orale."),
            ("Formation bureautique Excel/Word", "Initiation et perfectionnement aux outils Microsoft Office."),
            ("Atelier prise de parole en public", "Techniques pour gagner en aisance à l'oral."),
            ("Coaching orientation scolaire", "Aide à la définition du projet d'études et professionnel."),
            ("Préparation concours infirmier", "Entraînement aux épreuves écrites et orales."),
            ("Stage intensif vacances scolaires", "Révisions et approfondissement pendant les vacances."),
            ("Cours de programmation Python", "Découverte et perfectionnement en Python."),
            ("Formation e-learning gestion de projet", "Formation à distance sur les méthodes de gestion de projet."),
            ("Atelier méthodologie de travail", "Organisation, mémorisation, gestion du temps."),
            ("Préparation concours grandes écoles", "Coaching et entraînement aux concours d'entrée."),
            ("Cours de français langue étrangère", "Apprentissage du français pour non francophones."),
            ("Cours de soutien en physique-chimie", "Aide à la compréhension des notions clés."),
            ("Cours de soutien en histoire-géographie", "Révisions et approfondissement des programmes."),
            ("Préparation TOEIC/TOEFL", "Entraînement aux tests d'anglais internationaux."),
            ("Cours de philosophie", "Aide à la dissertation et à l'analyse de texte."),
            ("Cours de sciences économiques et sociales", "Soutien en SES pour le lycée."),
            ("Atelier orientation post-bac", "Aide au choix de filière et d'établissement supérieur."),
            ("Cours de mathématiques supérieures", "Soutien pour les étudiants en prépa ou licence."),
            ("Cours particuliers physique", "Soutien scolaire en physique collège/lycée."),
            ("Cours particuliers chimie", "Soutien scolaire en chimie collège/lycée."),
            ("Cours particuliers SVT", "Soutien scolaire en sciences de la vie et de la terre."),
            ("Cours particuliers espagnol", "Remise à niveau et préparation examens d'espagnol."),
            ("Cours particuliers allemand", "Remise à niveau et préparation examens d'allemand."),
            ("Cours particuliers chinois", "Initiation et perfectionnement en mandarin."),
            ("Cours particuliers italien", "Remise à niveau et préparation examens d'italien."),
            ("Cours particuliers philosophie", "Aide à la dissertation et à l'analyse de texte philosophique."),
            ("Cours particuliers informatique", "Soutien en algorithmique, programmation, bureautique."),
            ("Cours particuliers économie", "Soutien en économie pour lycée et supérieur."),
            ("Cours particuliers gestion", "Soutien en gestion, management, comptabilité."),
            ("Cours particuliers droit", "Soutien en droit pour licence ou concours."),
            ("Cours particuliers histoire", "Soutien en histoire pour collège, lycée, concours."),
            ("Cours particuliers géographie", "Soutien en géographie pour collège, lycée, concours."),
            ("Cours particuliers arts plastiques", "Aide à la préparation des épreuves artistiques."),
            ("Cours particuliers musique", "Soutien en solfège, instrument, composition."),
            ("Cours particuliers théâtre", "Préparation aux concours et auditions de théâtre."),
            ("Cours particuliers sport", "Coaching sportif et préparation physique."),
            ("Cours particuliers mathématiques supérieures", "Soutien pour étudiants en prépa, licence, école d'ingénieur."),
            ("Préparation concours Sciences Po", "Coaching et entraînement aux concours d'entrée."),
            ("Préparation concours médecine", "Entraînement aux épreuves de PACES/LAS."),
            ("Préparation concours écoles de commerce", "Coaching et entraînement aux concours d'entrée."),
            ("Préparation concours fonction publique", "Entraînement aux concours administratifs."),
            ("Préparation concours paramédicaux", "Entraînement aux concours infirmier, kiné, etc."),
            ("Préparation concours ingénieur", "Coaching et entraînement aux concours d'entrée."),
            ("Préparation concours magistrature", "Entraînement aux épreuves écrites et orales."),
            ("Préparation concours police/gendarmerie", "Entraînement aux épreuves physiques et écrites."),
            ("Préparation concours douanes", "Coaching et entraînement aux concours d'entrée."),
            ("Préparation concours ENA", "Coaching et entraînement aux concours d'entrée."),
            ("Préparation concours agrégation", "Entraînement aux épreuves écrites et orales."),
            ("Préparation concours CAPES", "Entraînement aux épreuves écrites et orales."),
            ("Préparation concours CRPE", "Entraînement au concours de professeur des écoles."),
            ("Préparation concours BTS/DUT", "Coaching et entraînement aux examens de BTS/DUT."),
            ("Préparation concours licence/master", "Coaching et entraînement aux examens universitaires."),
            ("Préparation concours brevet des collèges", "Coaching et entraînement à l'examen du brevet."),
            ("Préparation concours baccalauréat", "Coaching et entraînement à l'examen du bac toutes filières."),
            ("Coaching orientation professionnelle", "Aide à la définition du projet professionnel."),
            ("Coaching reconversion professionnelle", "Accompagnement dans le changement de carrière."),
            ("Coaching prise de parole en public", "Techniques pour gagner en aisance à l'oral professionnel."),
            ("Coaching gestion du stress étudiant", "Méthodes pour gérer le stress des examens."),
            ("Coaching méthodologie de travail", "Organisation, mémorisation, gestion du temps pour étudiants."),
            ("Coaching mémoire et concentration", "Techniques pour améliorer la mémoire et la concentration."),
            ("Coaching préparation oraux", "Préparation aux oraux de concours et examens."),
            ("Coaching préparation entretiens", "Préparation aux entretiens d'embauche ou de stage."),
            ("Coaching rédaction CV et lettre de motivation", "Aide à la rédaction de CV et lettres de motivation."),
            ("Coaching recherche de stage/alternance", "Accompagnement dans la recherche de stage ou alternance."),
            ("Coaching insertion professionnelle", "Aide à l'intégration sur le marché du travail."),
            ("Coaching développement personnel étudiant", "Accompagnement pour la confiance en soi et la motivation."),
            ("Coaching orientation internationale", "Aide à la préparation d'études à l'étranger."),
            ("Coaching préparation TOEIC/TOEFL", "Entraînement aux tests d'anglais internationaux."),
            ("Coaching préparation IELTS", "Entraînement au test d'anglais IELTS."),
            ("Coaching préparation DELF/DALF", "Entraînement aux tests de français langue étrangère."),
            ("Coaching préparation DELE", "Entraînement au test d'espagnol DELE."),
            ("Coaching préparation TestDaF", "Entraînement au test d'allemand TestDaF."),
            ("Coaching préparation JLPT", "Entraînement au test de japonais JLPT."),
            ("Coaching préparation HSK", "Entraînement au test de chinois HSK."),
            ("Coaching préparation Cambridge", "Entraînement aux examens Cambridge English."),
            ("Coaching préparation GMAT", "Entraînement au test d'admission GMAT."),
            ("Coaching préparation GRE", "Entraînement au test d'admission GRE."),
            ("Coaching préparation SAT", "Entraînement au test d'admission SAT."),
            ("Coaching préparation ACT", "Entraînement au test d'admission ACT."),
            ("Coaching préparation LSAT", "Entraînement au test d'admission LSAT."),
            ("Coaching préparation MCAT", "Entraînement au test d'admission MCAT."),
            ("Coaching préparation Bar Exam", "Entraînement à l'examen du barreau américain."),
            ("Coaching préparation CFA", "Entraînement à l'examen du Chartered Financial Analyst."),
            ("Coaching préparation CPA", "Entraînement à l'examen du Certified Public Accountant."),
            ("Coaching préparation PMP", "Entraînement à la certification Project Management Professional."),
            ("Coaching préparation ITIL", "Entraînement à la certification ITIL."),
            ("Coaching préparation Prince2", "Entraînement à la certification Prince2."),
            ("Coaching préparation Scrum Master", "Entraînement à la certification Scrum Master."),
            ("Coaching préparation Google Analytics", "Entraînement à la certification Google Analytics."),
            ("Coaching préparation Microsoft Office Specialist", "Entraînement à la certification MOS."),
            ("Coaching préparation Adobe Certified Expert", "Entraînement à la certification Adobe."),
            ("Coaching préparation Cisco CCNA", "Entraînement à la certification Cisco CCNA."),
            ("Coaching préparation AWS Certified Solutions Architect", "Entraînement à la certification AWS."),
            ("Coaching préparation Azure Fundamentals", "Entraînement à la certification Microsoft Azure."),
            ("Coaching préparation Google Cloud Certified", "Entraînement à la certification Google Cloud."),
            ("Coaching préparation Salesforce Certified", "Entraînement à la certification Salesforce."),
            ("Coaching préparation Oracle Certified", "Entraînement à la certification Oracle."),
            ("Coaching préparation SAP Certified", "Entraînement à la certification SAP."),
            ("Coaching préparation IT Security", "Entraînement à la certification sécurité informatique."),
            ("Coaching préparation Data Science", "Entraînement à la certification data science."),
            ("Coaching préparation Cloud Computing", "Entraînement à la certification cloud computing."),
            ("Coaching préparation DevOps", "Entraînement à la certification DevOps."),
            ("Coaching préparation Blockchain", "Entraînement à la certification blockchain."),
            ("Coaching préparation Intelligence Artificielle", "Entraînement à la certification IA."),
            ("Coaching préparation Big Data", "Entraînement à la certification big data."),
            ("Coaching préparation IoT", "Entraînement à la certification Internet des Objets."),
            ("Coaching préparation Robotique", "Entraînement à la certification robotique."),
            ("Coaching préparation Mathématiques Appliquées", "Entraînement à la certification mathématiques appliquées."),
        ]
    },
    {
        "nom": "Finance",
        "prestations": [
            ("Tenue de comptabilité annuelle", "Saisie, révision et clôture des comptes d'entreprise."),
            ("Déclaration fiscale personnelle", "Optimisation et déclaration d'impôts sur le revenu."),
            ("Conseil en investissement immobilier", "Étude de rentabilité et accompagnement achat locatif."),
            ("Audit de gestion financière", "Analyse des flux et recommandations d'optimisation."),
            ("Montage dossier de crédit", "Constitution et suivi de dossiers de financement."),
            ("Gestion de portefeuille boursier", "Conseil et suivi d'investissements en actions/obligations."),
            ("Assurance vie et prévoyance", "Proposition de contrats adaptés à la situation du client."),
            ("Conseil en transmission d'entreprise", "Optimisation fiscale et juridique de la cession."),
            ("Accompagnement création d'entreprise", "Business plan, choix du statut, démarches administratives."),
            ("Externalisation paie", "Gestion des bulletins de salaire et déclarations sociales."),
            ("Conseil en défiscalisation", "Solutions pour réduire la pression fiscale légale."),
            ("Conseil en gestion de patrimoine", "Optimisation de l'épargne et des placements."),
            ("Conseil en fusion-acquisition", "Accompagnement lors de rachats ou fusions d'entreprises."),
            ("Gestion de trésorerie", "Optimisation des flux de trésorerie d'entreprise."),
            ("Conseil en financement participatif", "Aide à la levée de fonds via crowdfunding."),
            ("Audit de conformité réglementaire", "Vérification du respect des normes financières."),
            ("Conseil en fiscalité internationale", "Optimisation fiscale pour entreprises à l'étranger."),
            ("Gestion des risques financiers", "Mise en place de stratégies de couverture des risques."),
            ("Conseil en retraite", "Préparation et optimisation de la retraite."),
            ("Conseil en assurance emprunteur", "Choix et négociation d'assurance pour crédits."),
            ("Audit comptable et financier", "Vérification des comptes et analyse financière approfondie."),
            ("Gestion de la paie internationale", "Gestion des salaires pour filiales à l'étranger."),
            ("Gestion des notes de frais", "Mise en place de solutions de gestion des dépenses professionnelles."),
            ("Gestion des immobilisations", "Suivi et amortissement des actifs de l'entreprise."),
            ("Gestion des stocks et inventaires", "Optimisation des stocks et valorisation des inventaires."),
            ("Gestion des créances clients", "Suivi et relance des factures impayées."),
            ("Gestion des dettes fournisseurs", "Optimisation des règlements et négociation des délais."),
            ("Gestion des flux de trésorerie", "Prévision et suivi des entrées/sorties de fonds."),
            ("Gestion des investissements financiers", "Placement de trésorerie et gestion des risques."),
            ("Gestion des placements immobiliers", "Optimisation de la rentabilité locative."),
            ("Gestion des contrats d'assurance", "Suivi et optimisation des polices d'assurance."),
            ("Gestion des déclarations sociales", "Déclarations URSSAF, retraite, prévoyance, etc."),
            ("Gestion des déclarations fiscales", "TVA, IS, CFE, CVAE, etc."),
            ("Gestion des subventions publiques", "Recherche et obtention d'aides et subventions."),
            ("Gestion des levées de fonds", "Accompagnement dans la recherche d'investisseurs."),
            ("Gestion des opérations de fusion", "Conseil et accompagnement lors de fusions d'entreprises."),
            ("Gestion des opérations de scission", "Accompagnement lors de la séparation d'activités."),
            ("Gestion des opérations de cession", "Conseil lors de la vente d'entreprise ou d'actifs."),
            ("Gestion des opérations de LBO", "Montage et suivi des opérations de leveraged buy-out."),
            ("Gestion des opérations de MBO", "Montage et suivi des opérations de management buy-out."),
            ("Gestion des opérations de MBI", "Montage et suivi des opérations de management buy-in."),
            ("Gestion des opérations de capital risque", "Accompagnement dans l'investissement en start-up."),
            ("Gestion des opérations de private equity", "Gestion de fonds d'investissement privés."),
            ("Gestion des opérations de titrisation", "Montage d'opérations de titrisation d'actifs."),
            ("Gestion des opérations de financement structuré", "Montage de financements complexes."),
            ("Gestion des opérations de financement de projet", "Montage de financements pour projets d'infrastructure."),
            ("Gestion des opérations de financement export", "Accompagnement dans le financement des exportations."),
            ("Gestion des opérations de financement immobilier", "Montage de financements pour acquisitions immobilières."),
            ("Gestion des opérations de financement d'acquisition", "Montage de financements pour rachats d'entreprises."),
            ("Gestion des opérations de financement d'actifs", "Montage de financements pour équipements et matériels."),
            ("Gestion des opérations de financement de stocks", "Montage de financements pour stocks et matières premières."),
            ("Gestion des opérations de financement de créances", "Montage de financements pour créances clients."),
            ("Gestion des opérations de financement de trésorerie", "Montage de financements pour besoins de trésorerie."),
            ("Gestion des opérations de financement de croissance", "Montage de financements pour développement d'entreprise."),
            ("Gestion des opérations de financement de transmission", "Montage de financements pour transmission d'entreprise."),
            ("Gestion des opérations de financement de restructuration", "Montage de financements pour restructuration d'entreprise."),
            ("Gestion des opérations de financement de retournement", "Montage de financements pour entreprises en difficulté."),
            ("Gestion des opérations de financement de start-up", "Montage de financements pour jeunes entreprises innovantes."),
            ("Gestion des opérations de financement de PME", "Montage de financements pour petites et moyennes entreprises."),
            ("Gestion des opérations de financement de grands groupes", "Montage de financements pour grandes entreprises."),
            ("Gestion des opérations de financement de collectivités", "Montage de financements pour collectivités publiques."),
            ("Gestion des opérations de financement de projets publics", "Montage de financements pour projets publics."),
            ("Gestion des opérations de financement de projets privés", "Montage de financements pour projets privés."),
            ("Gestion des opérations de financement de projets internationaux", "Montage de financements pour projets à l'étranger."),
            ("Gestion des opérations de financement de projets innovants", "Montage de financements pour projets innovants."),
            ("Gestion des opérations de financement de projets durables", "Montage de financements pour projets à impact environnemental."),
            ("Gestion des opérations de financement de projets sociaux", "Montage de financements pour projets à impact social."),
            ("Gestion des opérations de financement de projets culturels", "Montage de financements pour projets culturels."),
            ("Gestion des opérations de financement de projets sportifs", "Montage de financements pour projets sportifs."),
            ("Gestion des opérations de financement de projets éducatifs", "Montage de financements pour projets éducatifs."),
            ("Gestion des opérations de financement de projets de santé", "Montage de financements pour projets de santé."),
            ("Gestion des opérations de financement de projets agricoles", "Montage de financements pour projets agricoles."),
            ("Gestion des opérations de financement de projets industriels", "Montage de financements pour projets industriels."),
            ("Gestion des opérations de financement de projets technologiques", "Montage de financements pour projets technologiques."),
            ("Gestion des opérations de financement de projets environnementaux", "Montage de financements pour projets écologiques."),
        ]
    },
    {
        "nom": "Marketing",
        "prestations": [
            ("Audit de présence digitale", "Analyse de la visibilité en ligne et recommandations."),
            ("Création de site vitrine", "Conception d'un site web pour présenter une activité."),
            ("Gestion de campagne Google Ads", "Mise en place et suivi de campagnes publicitaires."),
            ("Community management Instagram", "Animation et modération d'une communauté sur Instagram."),
            ("Création de contenu vidéo", "Réalisation de vidéos promotionnelles pour le web."),
            ("Rédaction d'articles de blog", "Production de contenus optimisés SEO."),
            ("Stratégie de marque", "Définition de l'identité et du positionnement de marque."),
            ("Emailing commercial", "Conception et envoi de newsletters ciblées."),
            ("Organisation d'événements", "Gestion de salons, conférences, lancements de produits."),
            ("Création de supports print", "Conception de flyers, affiches, brochures."),
            ("Veille concurrentielle", "Analyse des concurrents et tendances du marché."),
            ("Gestion de campagne Facebook Ads", "Création et suivi de publicités Facebook."),
            ("Création de charte graphique", "Définition de l'identité visuelle d'une marque."),
            ("Gestion d'influenceurs", "Collaboration avec des influenceurs pour promouvoir une marque."),
            ("Création de podcasts", "Production et diffusion de podcasts de marque."),
            ("Gestion de crise e-réputation", "Stratégies pour gérer une crise sur internet."),
            ("Création de newsletters", "Conception et routage de newsletters professionnelles."),
            ("Animation de webinaires", "Organisation et animation de séminaires en ligne."),
            ("Création de landing pages", "Pages d'atterrissage optimisées pour la conversion."),
            ("Gestion de base de données clients", "Segmentation et gestion de fichiers clients."),
            ("Création de campagne TikTok Ads", "Conception et gestion de publicités sur TikTok."),
            ("Gestion de campagne LinkedIn Ads", "Publicité ciblée pour le B2B sur LinkedIn."),
            ("Création de motion design", "Réalisation de vidéos animées pour le web et les réseaux sociaux."),
            ("Création de brand content", "Production de contenus de marque engageants."),
            ("Gestion de campagnes d'influence micro-influenceurs", "Collaboration avec des influenceurs de niche."),
            ("Création de jeux concours en ligne", "Organisation de concours pour générer de l'engagement."),
            ("Gestion de campagnes SMS marketing", "Envoi de campagnes promotionnelles par SMS."),
            ("Création de chatbot marketing", "Développement de bots pour l'acquisition et la fidélisation."),
            ("Création de mini-sites événementiels", "Sites web dédiés à des événements ou lancements."),
            ("Création de campagnes d'affichage urbain", "Gestion de la publicité sur mobilier urbain."),
            ("Création de PLV (publicité sur lieu de vente)", "Conception de supports pour magasins et salons."),
            ("Création de packaging produit", "Design et conception d'emballages attractifs."),
            ("Création de spots radio", "Production de publicités audio pour la radio."),
            ("Création de spots TV", "Production de publicités vidéo pour la télévision."),
            ("Création de podcasts de marque", "Production de podcasts pour renforcer la notoriété."),
            ("Création de newsletters automatisées", "Mise en place de scénarios d'e-mailing automatisés."),
            ("Création de campagnes de retargeting", "Reciblage publicitaire pour augmenter la conversion."),
            ("Création de campagnes display", "Publicité graphique sur sites web partenaires."),
            ("Création de campagnes native advertising", "Publicité intégrée au contenu éditorial."),
            ("Création de campagnes programmatique", "Achat automatisé d'espaces publicitaires en temps réel."),
            ("Création de campagnes d'affiliation", "Mise en place de partenariats rémunérés à la performance."),
            ("Création de campagnes d'inbound marketing", "Stratégies pour attirer et convertir des prospects."),
            ("Création de campagnes outbound marketing", "Prospection active et campagnes sortantes."),
            ("Création de campagnes de marketing automation", "Automatisation des tâches marketing répétitives."),
            ("Création de campagnes de lead nurturing", "Accompagnement des prospects jusqu'à la vente."),
            ("Création de campagnes de lead scoring", "Qualification automatique des prospects."),
            ("Création de campagnes de fidélisation", "Stratégies pour augmenter la rétention client."),
            ("Création de campagnes de parrainage", "Mise en place de programmes de recommandation."),
            ("Création de campagnes de co-marketing", "Partenariats entre marques pour des campagnes communes."),
            ("Création de campagnes de street marketing", "Actions de communication dans l'espace public."),
            ("Création de campagnes de marketing sensoriel", "Utilisation des sens pour renforcer l'expérience client."),
            ("Création de campagnes de marketing expérientiel", "Mise en place d'événements immersifs pour la marque."),
            ("Création de campagnes de marketing d'influence B2B", "Collaboration avec des experts du secteur."),
            ("Création de campagnes de marketing d'influence B2C", "Collaboration avec des influenceurs grand public."),
            ("Création de campagnes de marketing viral", "Stratégies pour générer du bouche-à-oreille massif."),
            ("Création de campagnes de marketing de contenu", "Production de contenus à forte valeur ajoutée."),
            ("Création de campagnes de marketing conversationnel", "Utilisation de la messagerie instantanée pour le marketing."),
            ("Création de campagnes de marketing mobile", "Stratégies pour toucher les utilisateurs de smartphones."),
            ("Création de campagnes de marketing local", "Ciblage géographique des prospects et clients."),
            ("Création de campagnes de marketing international", "Stratégies pour développer la marque à l'étranger."),
            ("Création de campagnes de marketing RSE", "Communication sur les engagements responsables de la marque."),
            ("Création de campagnes de marketing durable", "Stratégies pour promouvoir des produits/services éco-responsables."),
            ("Création de campagnes de marketing inclusif", "Communication adaptée à tous les publics."),
            ("Création de campagnes de marketing générationnel", "Ciblage par tranche d'âge (Gen Z, Millennials, etc.)."),
            ("Création de campagnes de marketing ethnique", "Ciblage de communautés culturelles spécifiques."),
            ("Création de campagnes de marketing sportif", "Sponsoring et communication autour du sport."),
            ("Création de campagnes de marketing événementiel", "Organisation d'événements pour promouvoir la marque."),
            ("Création de campagnes de marketing relationnel", "Développement de la relation client sur le long terme."),
            ("Création de campagnes de marketing participatif", "Impliquer les clients dans la création de produits/services."),
            ("Création de campagnes de marketing collaboratif", "Co-création de produits/services avec d'autres entreprises."),
            ("Création de campagnes de marketing communautaire", "Animation et développement de communautés de marque."),
            ("Création de campagnes de marketing expérimental", "Tests de nouveaux concepts marketing innovants."),
        ]
    },
    {
        "nom": "Juridique",
        "prestations": [
            ("Consultation droit du travail", "Conseil sur contrats, licenciements, litiges employeur/salarié."),
            ("Rédaction de statuts de société", "Création ou modification des statuts juridiques."),
            ("Assistance en droit immobilier", "Conseil sur baux, ventes, litiges immobiliers."),
            ("Rédaction de contrats commerciaux", "Élaboration de contrats de vente, prestation, partenariat."),
            ("Conseil en propriété intellectuelle", "Protection des marques, brevets, droits d'auteur."),
            ("Médiation et résolution de conflits", "Accompagnement à la résolution amiable des litiges."),
            ("Assistance en droit de la famille", "Divorce, garde d'enfants, successions."),
            ("Conseil en fiscalité des entreprises", "Optimisation et conformité fiscale des sociétés."),
            ("Défense devant les prud'hommes", "Représentation en cas de litige salarié/employeur."),
            ("Rédaction de CGV/CGU", "Rédaction de conditions générales de vente ou d'utilisation."),
            ("Conseil en droit des sociétés", "Fusions, acquisitions, restructurations."),
            ("Conseil en droit pénal", "Défense et conseil en matière pénale."),
            ("Conseil en droit des contrats", "Rédaction et analyse de contrats civils et commerciaux."),
            ("Conseil en droit fiscal", "Optimisation et conformité fiscale des particuliers et entreprises."),
            ("Conseil en droit international", "Conseil sur les litiges et contrats internationaux."),
            ("Conseil en droit de la consommation", "Litiges entre consommateurs et professionnels."),
            ("Conseil en droit administratif", "Litiges avec l'administration, marchés publics."),
            ("Conseil en droit social", "Conseil sur la protection sociale et la sécurité sociale."),
            ("Conseil en droit bancaire", "Litiges et conseils sur les produits bancaires."),
            ("Conseil en droit immobilier commercial", "Baux commerciaux, ventes, acquisitions."),
            ("Rédaction de pacte d'associés", "Rédaction et négociation de pactes d'actionnaires."),
            ("Rédaction de contrats de travail", "Élaboration de contrats CDI, CDD, alternance, etc."),
            ("Rédaction de contrats de prestation de service", "Contrats pour freelances, sous-traitants, etc."),
            ("Rédaction de contrats de location", "Baux d'habitation, commerciaux, professionnels."),
            ("Rédaction de contrats de franchise", "Contrats pour réseaux de franchise."),
            ("Rédaction de contrats de partenariat", "Contrats de collaboration entre entreprises."),
            ("Rédaction de contrats de confidentialité (NDA)", "Protection des informations sensibles."),
            ("Rédaction de contrats de cession de droits", "Cession de droits d'auteur, brevets, marques."),
            ("Rédaction de contrats de licence", "Licences de logiciels, marques, brevets."),
            ("Rédaction de contrats de distribution", "Contrats de distribution exclusive ou sélective."),
            ("Rédaction de contrats d'apporteur d'affaires", "Contrats de commissionnement."),
            ("Rédaction de contrats de sous-traitance", "Contrats pour prestations externalisées."),
            ("Rédaction de contrats de maintenance", "Contrats pour maintenance informatique, industrielle, etc."),
            ("Rédaction de contrats de bail commercial", "Baux pour locaux commerciaux."),
            ("Rédaction de contrats de bail professionnel", "Baux pour professions libérales."),
            ("Rédaction de contrats de prêt", "Contrats de prêt entre particuliers ou entreprises."),
            ("Rédaction de contrats de sponsoring", "Contrats pour événements sportifs ou culturels."),
            ("Rédaction de contrats de mécénat", "Contrats pour soutien d'activités culturelles ou sociales."),
            ("Rédaction de contrats de mandat", "Contrats de représentation ou gestion."),
            ("Rédaction de contrats de fiducie", "Contrats de gestion de patrimoine."),
            ("Rédaction de contrats de vente internationale", "Contrats pour export/import."),
            ("Rédaction de contrats de joint-venture", "Contrats de coentreprise internationale."),
            ("Rédaction de contrats de fusion", "Contrats pour opérations de fusion-acquisition."),
            ("Rédaction de contrats de cession d'entreprise", "Contrats pour vente de sociétés."),
            ("Rédaction de contrats de distribution sélective", "Contrats pour réseaux de distribution."),
            ("Rédaction de contrats de franchise internationale", "Contrats pour réseaux à l'étranger."),
            ("Rédaction de contrats de partenariat public-privé", "Contrats pour projets publics/privés."),
            ("Rédaction de contrats de consortium", "Contrats pour groupements d'entreprises."),
            ("Rédaction de contrats de sous-traitance internationale", "Contrats pour prestations à l'étranger."),
            ("Rédaction de contrats de transfert de technologie", "Contrats pour cession/licence de technologies."),
            ("Rédaction de contrats de recherche et développement", "Contrats pour projets innovants."),
            ("Rédaction de contrats de confidentialité internationale", "NDA pour projets internationaux."),
            ("Rédaction de contrats de cession de fonds de commerce", "Contrats pour vente de fonds de commerce."),
            ("Rédaction de contrats de cession de parts sociales", "Contrats pour vente de parts de société."),
            ("Rédaction de contrats de cession d'actions", "Contrats pour vente d'actions."),
            ("Rédaction de contrats de cession de clientèle", "Contrats pour vente de portefeuille clients."),
            ("Rédaction de contrats de cession de brevets", "Contrats pour vente de brevets."),
            ("Rédaction de contrats de cession de marques", "Contrats pour vente de marques."),
            ("Rédaction de contrats de cession de logiciels", "Contrats pour vente de logiciels."),
            ("Rédaction de contrats de cession de bases de données", "Contrats pour vente de bases de données."),
            ("Rédaction de contrats de cession de site internet", "Contrats pour vente de sites web."),
            ("Rédaction de contrats de cession de nom de domaine", "Contrats pour vente de noms de domaine."),
            ("Rédaction de contrats de cession de droits voisins", "Contrats pour vente de droits voisins du droit d'auteur."),
            ("Rédaction de contrats de cession de droits à l'image", "Contrats pour vente de droits à l'image."),
            ("Rédaction de contrats de cession de droits de propriété industrielle", "Contrats pour vente de droits industriels."),
            ("Rédaction de contrats de cession de droits de propriété littéraire et artistique", "Contrats pour vente de droits d'auteur."),
            ("Rédaction de contrats de cession de droits de propriété intellectuelle", "Contrats pour vente de droits de PI."),
            ("Rédaction de contrats de cession de droits de propriété commerciale", "Contrats pour vente de droits commerciaux."),
            ("Rédaction de contrats de cession de droits de propriété foncière", "Contrats pour vente de droits fonciers."),
            ("Rédaction de contrats de cession de droits de propriété mobilière", "Contrats pour vente de droits mobiliers."),
            ("Rédaction de contrats de cession de droits de propriété immobilière", "Contrats pour vente de droits immobiliers."),
            ("Rédaction de contrats de cession de droits de propriété intellectuelle internationale", "Contrats pour vente de droits de PI à l'étranger."),
            ("Rédaction de contrats de cession de droits de propriété industrielle internationale", "Contrats pour vente de droits industriels à l'étranger."),
            ("Rédaction de contrats de cession de droits de propriété littéraire et artistique internationale", "Contrats pour vente de droits d'auteur à l'étranger."),
            ("Rédaction de contrats de cession de droits de propriété commerciale internationale", "Contrats pour vente de droits commerciaux à l'étranger."),
            ("Rédaction de contrats de cession de droits de propriété foncière internationale", "Contrats pour vente de droits fonciers à l'étranger."),
            ("Rédaction de contrats de cession de droits de propriété mobilière internationale", "Contrats pour vente de droits mobiliers à l'étranger."),
            ("Rédaction de contrats de cession de droits de propriété immobilière internationale", "Contrats pour vente de droits immobiliers à l'étranger."),
        ]
    },
]

def insert_fake_data():
    db = SessionLocal()
    # Création des catégories de métiers
    categories = {}
    for corps in corps_metiers:
        cat = models.CategorieMetier(nom=corps["nom"])
        db.add(cat)
        db.commit()
        categories[corps["nom"]] = cat
    # Génération de prestataires couvrant tous les corps de métiers
    prestataires = []
    prestations = []
    for i in range(1, 501):  # 500 prestataires
        corps = random.choice(corps_metiers)
        cat = categories[corps["nom"]]
        p = models.Prestataire(
            nom=f"{corps['nom']} Pro {i}",
            description=f"Prestataire spécialisé en {corps['nom'].lower()}.",
            email=f"{corps['nom'].lower()}pro{i}@test.com",
            telephone=f"06{random.randint(10,99)}{random.randint(10,99)}{random.randint(10,99)}{random.randint(10,99)}",
            categorie_metier_id=cat.id,
            note=round(random.uniform(5, 10), 2)  # note sur 10, entre 5 et 10
        )
        prestataires.append(p)
        db.add(p)
        db.commit()
        # 15 prestations aléatoires, sans doublon, pour ce prestataire
        prestations_choisies = random.sample(corps['prestations'], 25)
        for titre, description in prestations_choisies:
            prestations.append(models.Prestation(
                titre=titre,
                description=description,
                prix=random.randint(500, 10000),
                duree_estimee=random.randint(1, 30),
                prestataire_id=p.id,
                categorie_metier_id=cat.id
            ))
    # Ajout prestations
    for p in prestations:
        db.add(p)
    db.commit()
    # Génération de nombreux clients
    clients = [
        models.Client(
            nom=f"Client {i}",
            email=f"client{i}@test.com",
            telephone=f"07{random.randint(10,99)}{random.randint(10,99)}{random.randint(10,99)}{random.randint(10,99)}"
        )
        for i in range(1, 51)
    ]
    for c in clients:
        db.add(c)
    db.commit()
    
    # Génération de projets pour chaque client
    projets = [
        models.Projet(
            titre=f"Projet {i}",
            description=f"Description du projet {i}",
            client_id=random.randint(1, 50)
        )
        for i in range(1, 100)
    ]
    for p in projets:
        db.add(p)
    db.commit()
    db.close()

if __name__ == "__main__":
    insert_fake_data()